hydra:
  searchpath:
    - file://verl/trainer/config
    - file://configs/rl_trainer

defaults:
  - ppo_trainer
  - _self_

data:
  repeat:
    factor: null # Set to `null` to disable repeating
    shuffle_seed: ${seed} # Set to a negative number to disable shuffling
  val_repeat_factor: null # Set to `null` to disable repeating
  dynamic_max_resp_len:
    enable: True
    extending_tolerance: 0.2

reward_model:
  reward_manager: dapo
  overlong_buffer:
    enable: False
    len: 4096
    penalty_factor: 1.0
    log: True

algorithm:
  filter_groups:
    enable: True
    metric: acc # acc / score / seq_reward / seq_final_reward / ...
    max_num_gen_batches: 10 # Non-positive values mean no upper limit
    oversampling_factor: 1.2

trainer:
  project_name: verl_dapo

seed: 42
