data:
  path: /tmp/math_Qwen2-7B-Instruct.parquet
  prompt_key: prompt
  last_user_msg_template: null # Jinja template with the message dict as input, e.g., "{{ content | trim }}\n\nLet's think step by step."
  # NOTE: Shell string resolving is tricky. Better to override with yaml. c.f. scripts/print_hydra_config.py
  response_key: responses
  data_source_key: data_source
  reward_model_key: reward_model

custom_reward_function:
  path: null
  name: compute_score
